### ISSUE TITLE
sugestao-artigos-de-referencia

### ISSUE THREAD

**Issue by ghost** [woliveiras/linguagem-neutra-dev#1]
Segue sugestões de artigos de referência sobre o assunto:

-  [O USO DA LINGUAGEM NEUTRA COMO VISIBILIDADE E INCLUSÃO PARA PESSOAS TRANS NÃO-BINÁRIAS NA LÍNGUA PORTUGUESA: A VOZ “DEL@S” OU “DELXS”? NÃO! A VOZ “DELUS”! por Héliton Diego Lau - Universidade Federal do Paraná ](http://www.sies.uem.br/trabalhos/2017/3112.pdf)

- [Uma língua neutra como meio de inclusão social por Jorge Salhani](https://www2.faac.unesp.br/blog/obsmidia/2015/03/30/uma-lingua-neutra-como-meio-de-inclusao-social/)

**Comment by woliveiras** [comment]
Valeu @dan-primo
